backend/urls.py
# backend/urls.py

from django.contrib import admin
from django.urls import path, include                 
from rest_framework import routers                    
from todo import views                            

router = routers.DefaultRouter()                      
router.register(r'todos', views.TodoView, 'todo')
router.register(r'subtasks', views.SubtaskView, 'subtasks')
router.register(r'canvastodos', views.CanvasTodoView, 'canvastodos')

urlpatterns = [
    path('admin/', admin.site.urls),         
    path('api/', include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('todo.urls'))              
]

todo/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'todo'
urlpatterns = [
    path('<int:user_id>', views.index, name='index'),
    path('user', views.canvas_user, name='canvas_user'),
    path('log', views.log, name='log'),
    path('logout', views.out, name='out'),
    path('', views.home, name='home'),
    path('newtask', views.newtask, name='newtask'),
    path('task/<int:task_id>', views.task, name='task'),
    path('newsub/<int:task_id>', views.newsub, name='newsub'),
    path('canvas-link', views.canvas_link, name='link'),
    path('all/<int:user_id>', views.all, name='all'),
    path('complete/<int:task_id>', views.complete, name='complete'),
    path('undo/<int:task_id>', views.undo, name='undo'),
    path('complete-canvas/<int:task_id>', views.completecan, name='complete'),
    path('undo-canvas/<int:task_id>', views.undocan, name='undo'),
    path('complete/<int:task_id>/<int:sub_id>', views.completesub, name='complete'),
    path('undo/<int:task_id>/<int:sub_id>', views.undosub, name='undo'),
    path('unlink', views.unlink, name='unlink'),
    path('newuser', views.newuser, name='newuser'),
    path('error/<str:error_type>', views.error, name='error'),

]

todo/models.py
# todo/models.py

from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    due = models.DateTimeField(default = timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Subtask(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    parent = models.ForeignKey(Todo, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class CanvasTodo(models.Model):
    # todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    due = models.DateTimeField(default = timezone.now)
    link = models.URLField()
    assignment_id = models.IntegerField()
    course_id = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class CanvasUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    canvasLinked = models.BooleanField(default = False)
    APIkey = models.CharField(max_length=150, default=None, null=True)
    img = models.CharField(max_length=200, default=None, null=True)
    name = models.CharField(max_length=200, default=None, null=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        CanvasUser.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.canvasuser.save()

todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=256)
    password = forms.CharField(label="Password", max_length=256)

class TaskForm(forms.Form):
    name = forms.CharField(label="Task Name", max_length=120)
    description = forms.CharField(label="Description", max_length=500, widget=forms.Textarea())
    due = forms.DateTimeField(input_formats=('%m/%d/%Y %I:%M %p',))

class SubtaskForm(forms.Form):
    name = forms.CharField(label="Subtask Name", max_length=120)
    description = forms.CharField(label="Description", max_length=500, widget=forms.Textarea())

class CanvasAPIForm(forms.Form):
    APIKey = forms.CharField(label="API Key", max_length=256)

class NewUserForm(UserCreationForm):
    # username = forms.CharField(label="Username", max_length=32)
    # password = forms.CharField(label="Password", max_length=50)
    # password_conf = forms.CharField(label="Confirm Password", max_length=50)
    first_name = forms.CharField(label="First Name", required = True, max_length=30)
    last_name = forms.CharField(label="Last Name", required = True, max_length=30)
    email = forms.EmailField(label="Email", required = False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name',)

todo/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from rest_framework import viewsets
from .serializers import TodoSerializer, SubtaskSerializer, CanvasTodoSerializer
from .models import Todo, Subtask, CanvasTodo, User
from pip._vendor import requests
from .forms import LoginForm, TaskForm, SubtaskForm, CanvasAPIForm, NewUserForm                                                                                                                                        
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.contrib.auth.decorators import login_required

# Create your views here.

class TodoView(viewsets.ModelViewSet):
    serializer_class = TodoSerializer
    queryset = Todo.objects.all()

class SubtaskView(viewsets.ModelViewSet):
    serializer_class = SubtaskSerializer
    queryset = Subtask.objects.all()

class CanvasTodoView(viewsets.ModelViewSet):
    serializer_class = CanvasTodoSerializer
    queryset = CanvasTodo.objects.all()

def newuser(request):
    message = ''
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()

            raw = form.cleaned_data['password1']
            
            # if p1 == p2:

            username = form.cleaned_data['username']
            
            user = authenticate(username=username, password=raw)
            
            login(request, user)

            return HttpResponseRedirect('/')

        else:
             message = 'Your passwords did not match.'   
        #     return HttpResponseRedirect('/error/pass')

    else:
        form = NewUserForm()

    return render(request, 'todo/newuser.html', {'form':form, 'message': message})


def error(request, error_type):
    if error_type == 'pass':
        message= 'Your passwords did not match.'
    elif error_type == 'login':
        message = 'Invalid username or password.'
    else: 
        message = 'How did you get here? You are not supposed to be here. Please leave now. There will be C O N S E Q U E N C E S.'
    return render(request, 'todo/error.html', {'message':message})


def log(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                # print('if')
                login(request, user)
                logstring = '/' + str(user.id)
                return HttpResponseRedirect(redirect_to=logstring)

            else:
                # print('else')
                return HttpResponseRedirect(redirect_to='/error/login')


    else:
        form = LoginForm()

        return render(request, 'todo/login.html', {'form':form})

def out(request):
    logout(request)
    return(HttpResponseRedirect('/log'))

def home(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/log')

    else:
        returnstr = '/' + str(request.user.id)
        return HttpResponseRedirect(returnstr)

@login_required
def newtask(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            due = form.cleaned_data['due']

            t = Todo(title=name, description=description, due=due, user=user)
            t.save()
            return HttpResponseRedirect('/')

    else:
        form = TaskForm()
        return render(request, 'todo/newtask.html', {'form':form})

    return render(request, 'todo/newtask.html', {'form':form})

@login_required
def newsub(request, task_id):
    task = get_object_or_404(Todo, pk=task_id)
    if request.user == task.user:
        if request.method == 'POST':
            form = SubtaskForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                description = form.cleaned_data['description']
                s = Subtask(title=name, description=description, parent=task)
                s.save()
                return HttpResponseRedirect('/task/' + str(task_id))
        else:
            form = SubtaskForm()
            return render(request, 'todo/newsub.html', {'form':form, 'task':task})
    else:
        current = request.user.id
        return HttpResponseRedirect('/' + str(current))


@login_required
def canvas_link(request):
    user = get_object_or_404(User, id=request.user.id)
    if request.method == 'POST':
        form = CanvasAPIForm(request.POST)
        if form.is_valid():
            key = form.cleaned_data['APIKey']

            user.canvasuser.APIkey = key
            user.canvasuser.canvasLinked = True
            user.save()
            return HttpResponseRedirect('/user')

    else:
        form = CanvasAPIForm()
        return render(request, 'todo/canvas_link.html', {'form':form})


@login_required
def complete(request, task_id):
    task = get_object_or_404(Todo, id=task_id)
    if task.user == request.user:
        task.completed=True
        task.save()

    return HttpResponseRedirect('/')


@login_required
def completecan(request, task_id):
    task = get_object_or_404(CanvasTodo, id=task_id)
    if task.user == request.user:
        task.completed=True
        task.save()

    return HttpResponseRedirect('/')


@login_required
def completesub(request, task_id, sub_id):
    task = get_object_or_404(Todo, id=task_id)
    sub = get_object_or_404(Subtask, id=sub_id)
    
    if task.user == request.user:
        sub.completed=True
        sub.save()

    return HttpResponseRedirect('/task/'+str(task.id))


@login_required
def undo(request, task_id):
    task = get_object_or_404(Todo, id=task_id)
    if task.user == request.user:
        task.completed=False
        task.save()

    return HttpResponseRedirect('/')

@login_required
def undocan(request, task_id):
    task = get_object_or_404(CanvasTodo, id=task_id)
    if task.user == request.user:
        task.completed=False
        task.save()

    return HttpResponseRedirect('/')

@login_required
def undosub(request, task_id, sub_id):
    task = get_object_or_404(Todo, id=task_id)
    sub = get_object_or_404(Subtask, id=sub_id)
    
    if task.user == request.user:
        sub.completed=False
        sub.save()

    return HttpResponseRedirect('/task/'+str(task.id))





@login_required
def task(request, task_id):
    task = get_object_or_404(Todo, pk=task_id)
    if request.user == task.user:
        subs = Subtask.objects.filter(parent=task)
        return render(request, 'todo/task.html', {'task':task, 'subs':subs})
    else:
        current = request.user.id
        return HttpResponseRedirect('/' + str(current))


@login_required
def index(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # user = User.objects.get(id=user_id)
    if user == request.user:
        tasks = (Todo.objects.filter(user=user))
        tasks = tasks.filter(completed=False)
        tasks = tasks.order_by('due')
        # tasks.append(CanvasTodo.objects.filter(user=user))
        subtasks = Subtask.objects.all()
        show_all = False

        canvas = CanvasTodo.objects.filter(user=user)
        canvas = canvas.filter(completed=False)
        return render(request, 'todo/index.html', {'tasks': tasks, "subtasks":subtasks, "user":user, "show_all":show_all, "canvas":canvas,})

    else:
        current = request.user.id
        return HttpResponseRedirect('/' + str(current))

@login_required
def all(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # user = User.objects.get(id=user_id)
    if user == request.user:
        tasks = (Todo.objects.filter(user=user))
        
        tasks = tasks.order_by('due')
        # tasks.append(CanvasTodo.objects.filter(user=user))
        subtasks = Subtask.objects.all()
        show_all = True
        canvas = CanvasTodo.objects.filter(user=user)
        return render(request, 'todo/index.html', {'tasks': tasks, "subtasks":subtasks, "user":user, "show_all":show_all, "canvas":canvas,})

    else:
        current = request.user.id
        return HttpResponseRedirect('/' + str(current))
@login_required
def unlink(request):
    user = request.user
    for t in CanvasTodo.objects.filter(user=user):
        t.delete()
    user.canvasuser.canvasLinked = False
    user.save()
    return HttpResponseRedirect('/')


@login_required
def canvas_user(request):
    user = User.objects.get(id=request.user.id)
    if not user.canvasuser.canvasLinked:
        return HttpResponseRedirect('/canvas-link')

    access_token = user.canvasuser.APIkey

    getstring = "https://westminster.instructure.com/api/v1/users/self?access_token=" + access_token
    response = requests.get(getstring)
    data = response.json()

    for key in data.keys():
        if key == 'errors':
    # if data.keys().contains('errors'):
            user.canvasuser.canvasLinked = False
            user.save()
            return HttpResponseRedirect('/')
    name = data['name']
    img = data['avatar_url']

    user.canvasuser.name = name
    user.canvasuser.img = img
    user.save()
    # print("\n")
    # for i in data:
    #     print(i, data[i])
    # print("\n")

    todostring = "https://westminster.instructure.com/api/v1/users/self/todo?access_token=" + access_token
    tosponse = requests.get(todostring)
    todo = tosponse.json()

    # for key in todo.keys():
    #     if key == 'errors':
    #         user.canvasuser.canvasLinked = False
    #         user.save()
    #         return HttpResponseRedirect('/')
    assignments = []

    # print("\n")
    for i in todo:
        # print(i)
        # print("\n \n")

templates/todo/base.html
{% load static %}
<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static '/todo/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static '/todo/css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class="page-header bg-light">
            <h1><a href="/">Frozen Water</a></h1>
            <h4><a href="/logout">Log Out</a></h4>
            {% block header %}
            {% endblock %}
        </div>
    </div>

    <div class="container">
        <div class="content-block">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class="container">
        <div class="page-footer">
            <p>Daniel Lier Senior Project 2020</p>
            {% block foot %}
            {% endblock %}
        </div>
    </div>
</body>

templates/todo/canvas_link.html
{% extends 'todo/base.html' %}
{% block head %}
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{% endblock %}



{% block content %}

<!-- <a href="/"><button>Cancel Adding Task</button></a> -->

<form method="post" action="/canvas-link">
    {% csrf_token %}
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Link Your Canvas Account</div>
            <div class="panel-body">
            <span><p>To get an API Key, go to your Canvas account settings and select "New Access Token" under Approved Integrations.</p></span>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.APIKey.label_tag }}</label>
                            {{ form.APIKey }}
                        </div>
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Link Account">

            </div>
        </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
</form>





<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<script>
    var x = document.getElementById("id_APIKey");
    x.className += "form-control";
</script>


{% endblock %}

templates/todo/canvas_user.html
{% extends 'todo/base.html' %}
{% block content %}
<head>
    <Title>Canvas User</Title>
</head>
  
  
<body>
    <h2>Canvas User</h2>
    <h3>Raw:</h3>
    <p>{{ data }}</p>
    <h3>Processed:</h3>
    <h4>Name: {{ name }}</h4>
    <h4>Avatar:<img src={{img}}> </h4>
    
    <h2><br><br>Todo List</h2>
    {% for a in assignments %}
    <h3>{{ a.name }}</h3>
    {{a.description|safe}}
    <p>Due date: {{a.due}}</p>
    <p><a href={{a.link}}>Link to assignment</a></p>
    <p>Assignment id: {{a.id}}</p>
    <p>Course id: {{a.course}}</p>
    <br>
    <br>


    {% endfor %}

    <h2><a href="/admin">Admin App</a></h2>
    {% endblock %}
</body>

templates/todo/error.html
{% extends 'todo/base.html' %}

{% block content %}
<h3>{{message}}</h3>
<p><a href="/"><button>Okay</button></a></p>
{% endblock %}

templates/todo/index.html
{% extends 'todo/base.html' %}

<body>
    {% block header %}
    <h5 ><a class="btn btn-info" href="/user">Import/Refresh Canvas Assignments</a></h5>
    {% endblock %}
    {% block content %}
    <div class="row">

        <div class="col-md-6">

            <h1>Hello, {{user.first_name}} ({{user}})</h1>

            <a href="/newtask"><button class="btn btn-info">New Task</button></a>

            {% if not show_all %}
            <a href="/all/{{user.id}}"><button class="btn btn-info">Show All Tasks</button></a>
            {% else %}
            <a href="/{{user.id}}"><button class="btn btn-info">Show Incomplete Tasks Only</button></a>
            {% endif %}

            <h2>Tasks</h2>
            <!-- <ul> -->
                {% for t in tasks %}
                {% if t.completed %}
                <div class="text-success">
                {%else%}<div>{%endif%}
                    <!-- <li> -->
                        <a href="/task/{{t.id}}"><h3>{{ t }}</h3></a>
                        <p>Due date: {{t.due}}</p>
                        {% if t.completed %}<p class="text-success">Completed&nbsp;<a href="/undo/{{t.id}}"><button type="button" class="btn btn-warning">Undo</button></a></p>{% else %}<p><a
                        href="/complete/{{t.id}}"><button type="button" class="btn btn-success">Complete</button></a></p>{% endif %}
                        <!-- </li> -->
                        <br>
                    </div>
                {% endfor %}
            <!-- </ul> -->
        </div>

        <div class="col-md-6">
            {% if user.canvasuser.canvasLinked %}
            <img class="img-circle" src={{user.canvasuser.img}}>

            <h2>Canvas</h2>
            {% if user.canvasuser.name %}
            <h3>User: {{user.canvasuser.name}}</h3>
            {% endif %}
            {% for a in canvas %}
            {% if a.completed %}
                <div class="text-success">
                {%else%}<div>{%endif%}
            <h3><a href={{a.link}} target="_blank">{{ a.title }}</a></h3>
            {{a.description|safe}}
            <p>Due date: {{a.due}}</p>
            {% if a.completed %}
            <p>Completed&nbsp;<a href="/undo-canvas/{{a.id}}"><button type="button" class="btn btn-warning">Undo</button></a></p>
            {% else %}
            <p><a href="/complete-canvas/{{a.id}}"><button type="button" class="btn btn-success">Complete</button></a></p>
            {% endif %}
            <!-- <p><a href={{a.link}}>Link to assignment</a></p> -->
            </div>
            <br>
           

            {% endfor %}
            <br><br><br>
            <p><a href="/unlink">Click here to un-link your Canvas Account.</a></p>
            {% endif %}


        </div>
    </div>


    <br><br>
    <!-- <h2><a href="/admin">Admin App</a></h2> -->

    <!-- <h2><a href="/api">API</a></h2> -->

   

    
    {% endblock %}
</body>

templates/todo/login.html
{% extends 'todo/base.html' %}
{% block content %}

<form method="post" action="/log">
    {% csrf_token %}
    <div class="form-group">
        <table class="table-responsive table-condensed">
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="Log In" class="btn btn-primary">
        <input type="hidden" name="next" value="{{ next }}">
    </div>
</form>

<div>
    <br>
    <a href="/newuser">Create Account</a>
</div>

<script>
    var x = document.getElementById("id_password");
    if (x.type === "text") {
        x.type = "password";
    }
</script>

{% endblock %}

templates/todo/newsub.html
{% extends 'todo/base.html' %}
{% block head %}
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{% endblock %}



{% block content %}

<!-- <a href="/"><button>Cancel Adding Task</button></a> -->

<form method="post" action="/newsub/{{task.id}}">
    {% csrf_token %}
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Add a Subtask</div>
            <div class="panel-body">




                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.name.label_tag }}</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.description.label_tag }}</label><br>
                            {{ form.description }}
                        </div>
                    </div>


                </div>
                <input type="submit" class="btn btn-primary" value="Add Task">





            </div>
        </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
</form>





<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<script>
    var x = document.getElementById("id_name");
    var y = document.getElementById("id_description");
    x.className += "form-control";
    y.className += "form-control";
</script>


{% endblock %}

templates/todo/newtask.html
{% extends 'todo/base.html' %}
{% block head %}
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{% endblock %}



{% block content %}


<form method="post" action="/newtask">
    {% csrf_token %}
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Add a Task</div>
            <div class="panel-body">
                
                
                
                
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.name.label_tag }}</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class='col-md-6'>
                        <div class="form-group">
                            <label class="control-label">{{ form.due.label_tag }}</label>
                            
                            {{ form.due }}
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">{{ form.description.label_tag }}</label><br>
                            {{ form.description }}
                        </div>
                    </div>
                    
                    
                </div>
                <input type="submit" class="btn btn-primary" value="Add Task">
                
                
                
                
                
            </div>
        </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
</form>


<a href="/"><button class="btn btn-warning">Cancel Adding Task</button></a>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>


<script>
    $(function () {
        $('#id_due').datetimepicker();
    });
</script>

<script>
    var x = document.getElementById("id_name");
    var y = document.getElementById("id_description");
    var z = document.getElementById("id_due");
    x.className += "form-control";
    y.className += "form-control";
    z.className += "form-control";
</script>


{% endblock %}

templates/todo/task.html
{% extends 'todo/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>{{task.title}}</h1>
    </div>

    <div class="col-md-3">
        <h1>
            {% if not task.completed %}
            <p><a href="/complete/{{task.id}}""><button type=" button" class="btn btn-success">Complete this
                    Task</button></a></p>
            {% else %}
            <small class="text-right">This task is complete. <a href="/undo/{{task.id}}""><button type=" button"
                    class="btn btn-warning">Undo</button></a></small>
            {% endif %}

        </h1>
    </div>
</div>

<h2>Due date: {{task.due}}</h2>
<p class="well">{{task.description}}</p>

{% if subs %}
<h2>Subtasks</h2>
<table class="table">
    {% for s in subs %}
    {% if s.completed %}
    <tr class="success">
        {% else %}
    <tr>
        {% endif %}
        <td><strong>{{s.title}}</strong>:</td>
        <td>{{s.description}}</td>
        {% if not s.completed %}
        <td><a href="/complete/{{task.id}}/{{s.id}}"><button type="button" class="btn btn-success">Complete</button></a>
        </td>
        {% else %}
        <td>Done&nbsp;&nbsp;<a href="/undo/{{task.id}}/{{s.id}}""><button type=" button"
                class="btn btn-warning">Undo</button></a></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endif %}

<a href="/newsub/{{task.id}}"><button type="button" class="btn btn-primary">New Subtask</button></a>
<br>
<br>
{% endblock %}